language: cpp
sudo: true
dist: trusty
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - lcov
    env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - COVERAGE=ON
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
    env:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
branches:
  only:
  - master
before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir cmake-download &&
    cd cmake-download &&
    curl -O https://cmake.org/files/v3.10/cmake-3.10.0-rc5-Linux-x86_64.sh &&
    bash cmake-3.10.0-rc5-Linux-x86_64.sh --skip-license &&
    cd ..
script:
  - ./scripts/build.sh
after_success:
- for f in $(find build -name '*.gcno'); do gcov-6 $f; done
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage
  reports"
cache:
  directories:
    - "$HOME/.hunter/_Base/Cache"
env:
  global:
  - LANG="en_US.UTF-8"
  - PATH="$TRAVIS_BUILD_DIR/cmake-download/bin:$PATH"
